version: '3.1'

services:

  db:
    image: mariadb:10.4.10
    container_name: thermomix_db_server
    restart: always
    environment:
      MYSQL_DATABASE: thermomix
      MYSQL_ROOT_PASSWORD: Hola1234
      MYSQL_USER: thermomix
      MYSQL_PASSWORD: Hola1234
    ports:
      - "3306:3306"
    volumes:
      - ./thermomix.sql:/docker-entrypoint-initdb.d/thermomix.sql

  authentication:
    image: adomargon/node-authentication:1.0
    container_name: authentication_rest_server
    restart: always
    ports:
      - "8081:80"

  thermomix:
    image: adomargon/server_thermomix:0.10
    container_name: thermomix_rest_server
    ports:
      - "8082:8082"


  # docker exec -it thermomix_dbserver mariadb --database thermomix -u thermomix -p

  # docker commit thermomix_dbserver adomargon/thermomix_database:1.1
  # docker push adomargon/thermomix_db_server:1.1

  # docker run --name thermomix_db_server --publish 3306:3306 adomargon/thermomix_db_server:1.1
