### Retrieve token success
POST http://127.0.0.1:8081/api/login_user 
content-type: application/x-www-form-urlencoded

username=sonia.silverado
&password=s

### Retrieve books success
GET http://127.0.0.1:8082/api/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE2NzU3MDk0ODAsImV4cCI6MTY3NTcyMzg4MH0.NP5udC7SRXs-kKoaVtkWQ47Rwi8jdzSxq7tX4jig948


### Retrieve dishes success
GET http://127.0.0.1:8082/api/dishes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE2NzU3MDk0ODAsImV4cCI6MTY3NTcyMzg4MH0.NP5udC7SRXs-kKoaVtkWQ47Rwi8jdzSxq7tX4jig948


### Retrieve dishes by book id success
GET http://127.0.0.1:8082/api/book/6917/dishes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE2NzU3MDk0ODAsImV4cCI6MTY3NTcyMzg4MH0.NP5udC7SRXs-kKoaVtkWQ47Rwi8jdzSxq7tX4jig948

### Retrieve dishes by book id error
GET http://127.0.0.1:8082/api/book/691/dishes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE2NzU3MDk0ODAsImV4cCI6MTY3NTcyMzg4MH0.NP5udC7SRXs-kKoaVtkWQ47Rwi8jdzSxq7tX4jig948


### Retrieve dish by id success
GET http://127.0.0.1:8082/api/dish/691702
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE2NzU3MDk0ODAsImV4cCI6MTY3NTcyMzg4MH0.NP5udC7SRXs-kKoaVtkWQ47Rwi8jdzSxq7tX4jig948

### Retrieve dish by id error
GET http://127.0.0.1:8082/api/dish/69170
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE2NzU3MDk0ODAsImV4cCI6MTY3NTcyMzg4MH0.NP5udC7SRXs-kKoaVtkWQ47Rwi8jdzSxq7tX4jig948



### Retrieve recipes success
GET http://127.0.0.1:8082/api/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE2NzU3MDk0ODAsImV4cCI6MTY3NTcyMzg4MH0.NP5udC7SRXs-kKoaVtkWQ47Rwi8jdzSxq7tX4jig948


### Retrieve recipe by id success
GET http://127.0.0.1:8082/api/recipe/254703
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE2NzU3MDk0ODAsImV4cCI6MTY3NTcyMzg4MH0.NP5udC7SRXs-kKoaVtkWQ47Rwi8jdzSxq7tX4jig948

### Retrieve recipe by id error
GET http://127.0.0.1:8082/api/recipe/25470
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbmlhLnNpbHZlcmFkbyIsImZpcnN0bmFtZSI6IlNvbmlhIiwibGFzdG5hbWUiOiJTaWx2ZXJhZG8iLCJpYXQiOjE2NzU3MDk0ODAsImV4cCI6MTY3NTcyMzg4MH0.NP5udC7SRXs-kKoaVtkWQ47Rwi8jdzSxq7tX4jig948
